# -*- coding: utf-8 -*-
"""Diabetic_Nephropathy_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCgrRoBOinevFhDugjmrDdH8lMfVNEnB

#PHASE 1: EDA & Data collection
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Df_diabetic = pd.read_excel("Diabetic_Nephropathy_v1.xlsx")
Df_diabetic

Df_diabetic["Sex"] = Df_diabetic["Sex"].replace({
    "Female": 0,
    "Male": 1
})

Df_diabetic

Df_diabetic = Df_diabetic.rename(columns={
    "TG（mmoll）": "TG (mmol/L)",
    "TC（mmoll）": "TC (mmol/L)",
    "HDLC（mmoll）": "HDLC (mmol/L)",
    "LDLC（mmoll）": "LDLC (mmol/L)",
    "C-peptide (ng/ml）": "C-peptide (ng/mL)"
})



Df_diabetic.columns = Df_diabetic.columns.str.strip()

print("VARIABLES LIST")
for i, col in enumerate(Df_diabetic.columns):
    print(f"{i}: {col}")

print("***************************************************")
print("DATASET INFORMATION")
print(Df_diabetic.info())
print("***************************************************")
print("TYPE OF VARIABLES")
print(Df_diabetic.dtypes)
print("***************************************************")
print("DESCRIPTION OF THE DATA")
print(Df_diabetic.describe().T)

# Resumen estadístico visual

desc = Df_diabetic.describe().T

display(
    desc.style
    .background_gradient(cmap="Blues")
    .format("{:.2f}")
)

plt.figure(figsize=(12,8))

sns.heatmap(
    desc,
    annot=True,
    fmt=".2f",
    cmap="YlGnBu"
)

plt.title("Description of the Data")
plt.show()

print("\nPosibles valores atípicos:")
print(desc.sort_values("max", ascending=False)[["max"]].head(5))

missing_values = pd.DataFrame({
    "Missing": Df_diabetic.isnull().sum(),
    "Percentage (%)": round(Df_diabetic.isnull().mean()*100,2)
})

missing_values.sort_values(
    by="Percentage (%)",
    ascending=False
)

plt.figure(figsize=(12,5))

sns.heatmap(
    Df_diabetic.isnull(),
    cbar=False,
    yticklabels=False
)

plt.title("Missing Values Heatmap")

plt.show()

"""###Note: Untill here, we have two problems with the data:
- the mising values
- a outlier of 5210 mmHg for DBP
"""

Df_diabetic[Df_diabetic["DBP (mmHg)"] > 200]
#We identifie the number (ID) of the patient with the outlier value

# Variables continuas
clinical_vars = [
    "Height(cm)",
    "Weight(kg)",
    "BMI (kg/m2)",
    "SBP (mmHg)",
    "DBP (mmHg)",
    "HbA1c (%)",
    "FBG (mmol/L)",
    "TG (mmol/L)",
    "C-peptide (ng/mL)",
    "TC (mmol/L)",
    "HDLC (mmol/L)",
    "LDLC (mmol/L)"

]

for col in clinical_vars:

    Q1 = Df_diabetic[col].quantile(0.25)
    Q3 = Df_diabetic[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = Df_diabetic[
        (Df_diabetic[col] < lower) |
        (Df_diabetic[col] > upper)
    ]

    print("\n" + "="*60)
    print(col)
    print(f"IQR range: [{lower:.2f}, {upper:.2f}]")
    print(f"Outliers encontrados: {len(outliers)}")

    if len(outliers) > 0:
        display(
            outliers[[col]]
            .sort_values(by=col, ascending=False)
            .head(10)
        )

#In the line code before, we noticed that there were two values totally imposible for clinical relevance: DBP = 5210 mmHg, LDL = 195 mmol/L.
#We delete and in the next section we'll calculate another values with KNNImputer
Df_diabetic.loc[
    Df_diabetic["DBP (mmHg)"] > 200,
    "DBP (mmHg)"
] = np.nan

Df_diabetic.loc[
    Df_diabetic["LDLC (mmol/L)"] > 20,
    "LDLC (mmol/L)"
] = np.nan

# We do again the visual report of the data

desc = Df_diabetic.describe().T

display(
    desc.style
    .background_gradient(cmap="Blues")
    .format("{:.2f}")
)

plt.figure(figsize=(12,8))

sns.heatmap(
    desc,
    annot=True,
    fmt=".2f",
    cmap="YlGnBu"
)

plt.title("Description of the Data")
plt.show()

print("\nPosibles valores atípicos:")
print(desc.sort_values("max", ascending=False)[["max"]].head(5))

duplicates = Df_diabetic.duplicated().sum()

print("Duplicated rows:", duplicates)

Df_diabetic[Df_diabetic.duplicated(keep=False)]

'''
**Handling of Duplicate Records**

Several observations exhibited identical values across all recorded variables.
Because no unique patient identifier was available in the dataset, the origin of these duplicate records
could not be verified. Consequently, no records were removed, and all observations were retained in the analysis
to maintain data integrity and reproducibility.

'''

# ==========================================
# TARGET VARIABLE DISTRIBUTION (DN)
# ==========================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Summary table
dn_counts = Df_diabetic["Diabetic nephropathy (DN)"].value_counts().sort_index()
dn_percent = (
    Df_diabetic["Diabetic nephropathy (DN)"]
    .value_counts(normalize=True)
    .sort_index() * 100
)

dn_summary = pd.DataFrame({
    "Count": dn_counts,
    "Percentage (%)": dn_percent.round(2)
})

print("DISTRIBUTION OF DIABETIC NEPHROPATHY (DN)")
display(dn_summary)

# Bar plot
plt.figure(figsize=(6, 4))

sns.countplot(
    data=Df_diabetic,
    x="Diabetic nephropathy (DN)",
    hue="Diabetic nephropathy (DN)",
    palette=["skyblue", "salmon"],
    legend=False
)

plt.title("Class Distribution of Diabetic Nephropathy")
plt.xlabel("Diabetic Nephropathy (0 = No, 1 = Yes)")
plt.ylabel("Number of Patients")

plt.show()

class_ratio = Df_diabetic["Diabetic nephropathy (DN)"].mean()

print(f"Positive class ratio: {class_ratio:.3f}")

if class_ratio < 0.30:
    print("Imbalanced dataset")
else:
    print("Reasonably balanced dataset")

'''
Class imbalance assessment:

The target variable (Diabetic Nephropathy, DN) exhibits a moderate class
imbalance. The positive class proportion is 0.259 (25.9%), meaning that
approximately 74.1% of patients belong to the negative class (DN = 0) and
25.9% belong to the positive class (DN = 1), resulting in a class ratio of
approximately 2.8:1.

According to the predefined criterion (positive class ratio < 0.30), the
dataset is considered imbalanced. However, the imbalance is not severe and
the dataset size is relatively limited (n = 767), therefore no observations
will be removed during preprocessing.

The original class distribution will be preserved for exploratory analysis.
During model development
'''

corr_matrix = Df_diabetic.corr(
    numeric_only=True
)

corr_matrix

plt.figure(figsize=(14,10))

sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Matrix")

# Rotate x-axis labels
plt.xticks(rotation=70)

plt.show()

# ==========================================
# TARGET VARIABLE CORRELATION ANALYSIS
# ==========================================
# What it does: Extracts and sorts the Pearson correlation coefficients of all features
# specifically against the target variable, "Diabetic nephropathy (DN)".
#
# Why it is necessary: While the full heatmap shows multi-collinearity between all features,
# this step isolates the predictive power of each clinical variable regarding the disease.
# Sorting them helps quickly identify the strongest risk factors (high positive correlation)
# and protective factors (high negative correlation) for feature selection.

corr_dn = corr_matrix[
    "Diabetic nephropathy (DN)"
].sort_values(
    ascending=False
)

corr_dn

# ==========================================
# VISUALIZING FEATURE CORRELATION WITH TARGET
# ==========================================

# 1. Set the figure size for better readability
plt.figure(figsize=(8,6))

# 2. Drop the target variable itself to avoid plotting a redundant 1.0 correlation bar.
# 3. Plot the remaining values as a horizontal bar chart (kind="barh")
#    to easily compare which clinical features have the strongest positive or negative impact on DN.
corr_dn.drop(
    "Diabetic nephropathy (DN)"
).plot(
    kind="barh"
)

# 4. Add title and display the plot
plt.title("Feature Correlation with DN")

plt.show()

eda_summary = pd.DataFrame({

    "Metric":[
        "Rows",
        "Columns",
        "Duplicates",
        "Missing Values",
        "DN Prevalence (%)"
    ],

    "Value":[
        Df_diabetic.shape[0],
        Df_diabetic.shape[1],
        Df_diabetic.duplicated().sum(),
        Df_diabetic.isnull().sum().sum(),
        round(
            Df_diabetic["Diabetic nephropathy (DN)"].mean()*100,
            2
        )
    ]
})

eda_summary

# ==========================================
# VISUALIZING DISTRIBUTIONS WITH BOXPLOTS
# ==========================================
import math

# Using the 'clinical_vars' list defined in the EDA phase
num_vars = len(clinical_vars)
cols_grid = 4 # Number of columns in the grid
rows_grid = math.ceil(num_vars / cols_grid)

# Create the figure and axes
fig, axes = plt.subplots(rows_grid, cols_grid, figsize=(16, rows_grid * 4))
axes = axes.flatten() # Flatten the axes array for easy iteration

# Loop through each clinical variable and create its boxplot
for i, col in enumerate(clinical_vars):
    sns.boxplot(
        data=Df_diabetic,
        y=col,
        ax=axes[i],
        color="skyblue",
        width=0.4
    )
    axes[i].set_title(f"Boxplot of {col}", fontsize=12, pad=10)
    axes[i].set_ylabel(col)

# Remove any unused subplots (if the number of variables isn't a perfect multiple of columns)
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

# Adjust layout to prevent overlapping
plt.tight_layout()
plt.show()

"""#Phase 2: Preprocessing & Feature Engineering

"""

from sklearn.impute import KNNImputer

# ==========================
# CELL 1: MISSING VALUES + KNN IMPUTER
# ==========================

# 1) Summary of missing values BEFORE imputation
missing_summary = pd.DataFrame({
    "Missing": Df_diabetic.isnull().sum(),
    "Percentage (%)": (Df_diabetic.isnull().mean() * 100).round(2)
}).sort_values("Percentage (%)", ascending=False)

print("MISSING VALUES BEFORE IMPUTATION")
display(missing_summary.head(20))

# 2) Numeric columns to be imputed with KNN
numeric_cols = [
    "Age",
    "Diabetes duration (y)",
    "Height(cm)",
    "Weight(kg)",
    "BMI (kg/m2)",
    "SBP (mmHg)",
    "DBP (mmHg)",
    "HbA1c (%)",
    "FBG (mmol/L)",
    "TG (mmol/L)",
    "C-peptide (ng/mL)",
    "TC (mmol/L)",
    "HDLC (mmol/L)",
    "LDLC (mmol/L)"
]

# 3) Split features and target
target_col = "Diabetic nephropathy (DN)"
X = Df_diabetic.drop(columns=[target_col])
y = Df_diabetic[target_col]

# 4) Apply KNNImputer ONLY to numeric columns
imputer = KNNImputer(n_neighbors=5)

X_numeric_imputed = imputer.fit_transform(X[numeric_cols])
X_numeric_imputed = pd.DataFrame(
    X_numeric_imputed,
    columns=numeric_cols,
    index=X.index
)

# 5) Replace numeric columns in X with their imputed versions
X.update(X_numeric_imputed)

# 6) Check remaining NaNs in numeric columns AFTER imputation
missing_after = X[numeric_cols].isnull().sum()

print("\nMISSING VALUES IN NUMERIC COLUMNS AFTER KNN IMPUTATION:")
print(missing_after)



# 7) Reconstruct a full dataframe with target + updated features
Df_clean = X.copy()
Df_clean[target_col] = y

# 8) Descriptive statistics AFTER KNN imputation
desc = Df_clean.describe().T  # variables as rows

plt.figure(figsize=(14, 8))
sns.heatmap(desc, annot=True, fmt=".2f", cmap="YlGnBu")
plt.title("Description of the Data After KNN Imputation")
plt.show()

Df_clean = X.copy()
Df_clean[target_col] = y
# ==========================================
# VISUALIZING DISTRIBUTIONS WITH BOXPLOTS
# ==========================================
import math

# Using the 'clinical_vars' list defined in the EDA phase
num_vars = len(clinical_vars)
cols_grid = 4  # Number of columns in the grid
rows_grid = math.ceil(num_vars / cols_grid)

# Create the figure and axes
fig, axes = plt.subplots(rows_grid, cols_grid, figsize=(16, rows_grid * 4))
axes = axes.flatten()  # Flatten the axes array for easy iteration

# Loop through each clinical variable and create its boxplot
for i, col in enumerate(clinical_vars):
    sns.boxplot(
        data=Df_clean,   # <<< aquí usamos el dataframe con KNN
        y=col,
        ax=axes[i],
        color="skyblue",
        width=0.4
    )
    axes[i].set_title(f"Boxplot of {col}", fontsize=12, pad=10)
    axes[i].set_ylabel(col)

# Remove any unused subplots (if the number of variables isn't a perfect multiple of columns)
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

from sklearn.preprocessing import StandardScaler
import numpy as np

# ==========================
# CELL 2: FEATURE ENGINEERING + SCALING
# ==========================

# 1) Create engineered features based on clinical rationale
def add_engineered_features(df):
    df = df.copy()
    # Pulse pressure: hemodynamic load
    df["PP"] = df["SBP (mmHg)"] - df["DBP (mmHg)"]
    # Mean arterial pressure: average perfusion pressure
    df["MAP"] = (df["SBP (mmHg)"] + 2 * df["DBP (mmHg)"]) / 3
    # Non-HDL cholesterol: atherogenic lipoproteins
    df["Non_HDL"] = df["TC (mmol/L)"] - df["HDLC (mmol/L)"]
    # LDL / HDL ratio: balance between bad and protective cholesterol
    df["LDL_to_HDL"] = df["LDLC (mmol/L)"] / df["HDLC (mmol/L)"]
    # TyG index: surrogate of insulin resistance
    df["TyG"] = np.log(df["TG (mmol/L)"] * df["FBG (mmol/L)"] / 2)
    return df

# Apply feature engineering to X (already imputed in Cell 1)
X_fe = add_engineered_features(X)

print("Columns after feature engineering:")
print(X_fe.columns)

# 2) Select all numeric columns (original + engineered) for scaling
numeric_all = X_fe.select_dtypes(include=[np.number]).columns.tolist()

print("\nNumber of numeric features (original + engineered):", len(numeric_all))

# 3) Standard scaling
scaler = StandardScaler()
X_scaled_array = scaler.fit_transform(X_fe[numeric_all])

X_scaled = pd.DataFrame(
    X_scaled_array,
    columns=numeric_all,
    index=X_fe.index
)

print("\nShape of X_scaled:", X_scaled.shape)
print("First 10 columns of X_scaled:")
print(X_scaled.columns[:10])

X_scaled

"""
In the previous two cells, a structured preprocessing and feature engineering workflow was applied
to the original Diabetic Nephropathy dataset in order to prepare it for machine learning modeling.

First, we performed a careful inspection of the data quality. Obvious physiologically impossible
outliers (such as extremely high diastolic blood pressure and LDL values far beyond any realistic
clinical range) were identified and set to NaN so that they would not bias the analysis. Then we
quantified missing values across all variables and focused on the continuous clinical features
(age, diabetes duration, anthropometrics, blood pressure, glycemic markers, triglycerides, and
lipid profile), because these are the ones where numeric relationships between patients make sense
for distance‑based methods.

To handle missing data in these continuous variables, we applied KNNImputer with k=5 neighbors.
This method fills in missing entries by looking at similar patients in the feature space instead of
using simple mean or median values, which helps preserve the multivariate structure and realistic
clinical patterns in the dataset. After imputation, we verified that all numeric clinical
variables had zero missing values. At this point, we also separated the dataset into features (X)
and target (y), where the target corresponds to the binary label “Diabetic nephropathy (DN)”.

In the next cell, we implemented clinically motivated feature engineering, creating only derived
variables that are fully computable from the existing measurements and that have a clear
pathophysiological interpretation. Specifically, we added:
- Pulse Pressure (PP = SBP – DBP), capturing arterial stiffness and hemodynamic load.
- Mean Arterial Pressure (MAP = (SBP + 2*DBP) / 3), approximating average perfusion pressure.
- Non‑HDL cholesterol (Non_HDL = TC – HDLC), representing the pool of atherogenic lipoproteins.
- LDL/HDL ratio (LDL_to_HDL = LDLC / HDLC), reflecting the balance between “bad” and “protective”
  cholesterol.
- TyG index (TyG = ln(TG * FBG / 2)), a surrogate marker of insulin resistance based on fasting
  triglycerides and glucose.

These engineered features are widely used in cardiovascular and metabolic risk research and are
consistent with the clinical rationale and existing literature on diabetic complications, rather
than being arbitrary mathematical combinations.

After enriching the feature set with these new variables, we selected all numeric columns
(original continuous features plus the engineered ones) and applied standardization using
StandardScaler. This transformation rescales each numeric feature to have zero mean and unit
variance, which is important for many machine learning algorithms, especially those that are
sensitive to feature scales (such as distance‑based models and regularized linear models). The
result is a processed feature matrix (X_scaled) that is numerically well‑behaved and contains both
the original clinical information and a small set of clinically meaningful derived indices. This
matrix, together with the target vector y, is now ready to be used for train‑test splitting,
model training, and evaluation.
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.stats.outliers_influence import variance_inflation_factor

# ==========================
# CELL: MULTICOLLINEARITY DIAGNOSTICS (READ‑ONLY)
# ==========================

# Work on a copy to avoid changing any existing object
X_diag = X_scaled.copy()

# 1) Correlation matrix between predictors (Pearson)
corr_matrix = X_diag.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(
    corr_matrix,
    cmap="coolwarm",
    center=0,
    square=True,
    cbar_kws={"shrink": 0.8}
)
plt.title("Correlation matrix of scaled predictors")
plt.show()

# 2) List highly correlated pairs (above a threshold)
corr_threshold = 0.90
high_corr_pairs = []

cols = corr_matrix.columns
for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        r = corr_matrix.iloc[i, j]
        if abs(r) >= corr_threshold:
            high_corr_pairs.append((cols[i], cols[j], r))

print("\nHighly correlated pairs (|r| >= {:.2f}):".format(corr_threshold))
if not high_corr_pairs:
    print("No strongly correlated pairs found at this threshold.")
else:
    for v1, v2, r in high_corr_pairs:
        print(f"{v1}  <-->  {v2} : r = {r:.3f}")

# 3) Variance Inflation Factor (VIF) for each predictor
vif_data = pd.DataFrame()
vif_data["feature"] = X_diag.columns
vif_data["VIF"] = [
    variance_inflation_factor(X_diag.values, i)
    for i in range(X_diag.shape[1])
]

vif_data = vif_data.sort_values("VIF", ascending=False)

print("\nVariance Inflation Factor (VIF) for each feature:")
display(vif_data)

# 4) Simple rule‑of‑thumb guidance (no changes applied)
print(
    "\nInterpretation guideline (no features are removed here):\n"
    "- Correlation |r| >= 0.90 suggests very strong linear dependence between two predictors.\n"
    "- VIF > 5 (and especially > 10) indicates substantial multicollinearity.\n"
    "Use this table to decide whether it makes sense to apply feature selection methods\n"
    "such as LASSO or to manually drop one variable from highly redundant pairs."
)

"""Before building the predictive models, we explicitly assessed multicollinearity among all
predictors (original and engineered) using the correlation matrix and the Variance Inflation
Factor (VIF). The diagnostics showed very strong linear dependencies in several blocks of
variables. In particular, there was a high correlation between DBP and MAP, as well as between
TC and Non_HDL, and multiple predictors (SBP, DBP, PP, MAP, TC, HDLC, Non_HDL) exhibited
extremely high or even infinite VIF values. This indicates that many of the engineered features
(PP, MAP, Non_HDL, LDL_to_HDL) are almost linear combinations of the raw clinical measures
(SBP, DBP, TC, HDLC, LDLC).

From a clinical point of view, these engineered indices can still be valuable: they summarize
hemodynamic load (PP, MAP) or atherogenic lipid burden (Non_HDL, LDL_to_HDL) and are widely
used in cardiovascular and nephropathy research. However, their strong collinearity with the
underlying raw variables means that, in strictly linear models, coefficient estimates may become
unstable and hard to interpret. For this reason, future work could explore simplified feature
sets (e.g., keeping only one representative variable per highly correlated block) or apply
regularization-based feature selection (such as LASSO) to automatically decide which of these
indices to retain.

In the present study, we proceed to train machine learning models using the full set of scaled
features, including both original and engineered predictors. Tree-based ensembles (Random Forest
and XGBoost), Support Vector Machines with non-linear kernels, and neural networks are generally
more robust to multicollinearity than classical linear regression models, because they do not rely
on interpreting individual coefficients and can handle redundant predictors without violating key
assumptions. Therefore, the presence of highly correlated features is not expected to critically
affect the performance of these models, although it may be revisited in future investigations if
model simplification or interpretability become a priority.

#Phase 3: Generation of models
"""

from sklearn.model_selection import train_test_split

# ==========================
# TRAIN–TEST SPLIT
# ==========================

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,          # feature matrix (scaled)
    y,                 # target vector (DN label)
    test_size=0.30,    # 30% for test, 70% for train
    stratify=y,        # preserves class proportion in both sets
    random_state=42    # reproducible split
)

print("Train shape:", X_train.shape, y_train.shape)
print("Test shape:", X_test.shape, y_test.shape)



from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_auc_score, classification_report
from scipy.stats import randint

# ==========================
# CELL: Random Forest + RandomizedSearchCV
# ==========================

# 1) Base Random Forest model
rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1,
    class_weight=None  # you can set to "balanced" if needed
)

# 2) Hyperparameter search space
param_dist_rf = {
    "n_estimators": randint(100, 500),
    "max_depth": [None, 3, 5, 7, 9, 12],
    "min_samples_split": randint(2, 10),
    "min_samples_leaf": randint(1, 5),
    "max_features": ["sqrt", "log2", None],
    "bootstrap": [True, False]
}

# 3) RandomizedSearchCV
rf_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist_rf,
    n_iter=40,             # number of random combinations to try
    cv=5,                  # 5-fold cross-validation
    scoring="roc_auc",     # optimize AUC
    n_jobs=-1,
    random_state=42,
    verbose=1
)

rf_search.fit(X_train, y_train)

print("Best CV AUC (Random Forest):", rf_search.best_score_)
print("Best hyperparameters (Random Forest):")
print(rf_search.best_params_)

# 4) Evaluate best model on the test set
rf_best = rf_search.best_estimator_

y_pred_rf = rf_best.predict(X_test)
y_proba_rf = rf_best.predict_proba(X_test)[:, 1]

print("\nTest AUC (Random Forest):", roc_auc_score(y_test, y_proba_rf))
print("\nClassification report (Random Forest - test set):")
print(classification_report(y_test, y_pred_rf))

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_auc_score, classification_report, precision_score, recall_score, f1_score
from scipy.stats import randint
import numpy as np

# ==========================
# Random Forest + RandomizedSearchCV
# ==========================

# 1) Base Random Forest model
rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1,
    class_weight=None  # you can set to "balanced" if needed
)

# 2) Hyperparameter search space
param_dist_rf = {
    "n_estimators": randint(100, 500),
    "max_depth": [None, 3, 5, 7, 9, 12],
    "min_samples_split": randint(2, 10),
    "min_samples_leaf": randint(1, 5),
    "max_features": ["sqrt", "log2", None],
    "bootstrap": [True, False]
}

# 3) RandomizedSearchCV
rf_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist_rf,
    n_iter=40,             # number of random combinations to try
    cv=5,                  # 5-fold cross-validation
    scoring="roc_auc",     # optimize AUC
    n_jobs=-1,
    random_state=42,
    verbose=1
)

# Fit the model with hyperparameter search
rf_search.fit(X_train, y_train)

print("Best CV AUC (Random Forest):", rf_search.best_score_)
print("Best hyperparameters (Random Forest):")
print(rf_search.best_params_)

# 4) Evaluate best model on the test set
rf_best = rf_search.best_estimator_

# Predicted probabilities for the positive class (class 1)
y_proba_rf = rf_best.predict_proba(X_test)[:, 1]

print("\nTest AUC (Random Forest):", roc_auc_score(y_test, y_proba_rf))

# =======================================
# THRESHOLD EXPLORATION SECTION
# =======================================

# Define a range of thresholds to evaluate
thresholds = np.arange(0.10, 0.91, 0.05)  # from 0.10 to 0.90 with step 0.05

print("\nThreshold\tPrecision_1\tRecall_1\tF1_1")
best_f1 = -1.0
best_threshold = 0.5  # default

for thr in thresholds:
    # Convert probabilities to class predictions using current threshold
    y_pred_thr = (y_proba_rf >= thr).astype(int)

    # Compute metrics for the positive class (label 1)
    precision = precision_score(y_test, y_pred_thr, pos_label=1, zero_division=0)
    recall    = recall_score(y_test, y_pred_thr, pos_label=1, zero_division=0)
    f1        = f1_score(y_test, y_pred_thr, pos_label=1, zero_division=0)

    print(f"{thr:.2f}\t\t{precision:.3f}\t\t{recall:.3f}\t\t{f1:.3f}")

    # Keep track of the threshold with the best F1 for class 1
    if f1 > best_f1:
        best_f1 = f1
        best_threshold = thr

print(f"\nBest threshold by F1 for class 1: {best_threshold:.2f} (F1 = {best_f1:.3f})")

# =======================================
# FINAL CLASSIFICATION REPORT WITH BEST THRESHOLD
# =======================================

# Use the best threshold to generate final predictions
y_pred_rf_best_thr = (y_proba_rf >= best_threshold).astype(int)

print(f"\nClassification report (Random Forest - test set, threshold={best_threshold:.2f}):")
print(classification_report(y_test, y_pred_rf_best_thr))

from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_auc_score, classification_report
from scipy.stats import loguniform

# ==========================
# CELL: SVM (RBF) + RandomizedSearchCV
# ==========================

# 1) Base SVM model (RBF kernel)
svm = SVC(
    kernel="rbf",
    probability=True,   # needed to compute AUC (predict_proba)
    random_state=42
)

# 2) Hyperparameter search space
# C and gamma are searched on log-scale ranges
param_dist_svm = {
    "C": loguniform(1e-2, 1e3),        # from 0.01 to 1000
    "gamma": loguniform(1e-4, 1e1)     # from 1e-4 to 10
}

# 3) RandomizedSearchCV
svm_search = RandomizedSearchCV(
    estimator=svm,
    param_distributions=param_dist_svm,
    n_iter=40,              # number of random combinations
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=42,
    verbose=1
)

svm_search.fit(X_train, y_train)

print("Best CV AUC (SVM RBF):", svm_search.best_score_)
print("Best hyperparameters (SVM RBF):")
print(svm_search.best_params_)

# 4) Evaluate best SVM on the test set
svm_best = svm_search.best_estimator_

y_pred_svm = svm_best.predict(X_test)
y_proba_svm = svm_best.predict_proba(X_test)[:, 1]

print("\nTest AUC (SVM RBF):", roc_auc_score(y_test, y_proba_svm))
print("\nClassification report (SVM RBF - test set):")
print(classification_report(y_test, y_pred_svm))

from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)
from scipy.stats import loguniform
import numpy as np

# ==========================
# SVM (RBF) + RandomizedSearchCV
# ==========================

# 1) Base SVM model (RBF kernel)
svm = SVC(
    kernel="rbf",
    probability=True,   # needed to compute AUC (predict_proba)
    random_state=42
)

# 2) Hyperparameter search space
# C and gamma are searched on log-scale ranges
param_dist_svm = {
    "C": loguniform(1e-2, 1e3),       # from 0.01 to 1000
    "gamma": loguniform(1e-4, 1e1)    # from 1e-4 to 10
}

# 3) RandomizedSearchCV
svm_search = RandomizedSearchCV(
    estimator=svm,
    param_distributions=param_dist_svm,
    n_iter=40,              # number of random combinations
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=42,
    verbose=1
)

# Fit the SVM with hyperparameter search
svm_search.fit(X_train, y_train)

print("Best CV AUC (SVM RBF):", svm_search.best_score_)
print("Best hyperparameters (SVM RBF):")
print(svm_search.best_params_)

# 4) Evaluate best SVM on the test set
svm_best = svm_search.best_estimator_

# Predicted probabilities for the positive class (class 1)
y_proba_svm = svm_best.predict_proba(X_test)[:, 1]

print("\nTest AUC (SVM RBF):", roc_auc_score(y_test, y_proba_svm))

# =======================================
# THRESHOLD EXPLORATION SECTION
# =======================================

thresholds = np.arange(0.10, 0.91, 0.05)  # from 0.10 to 0.90 with step 0.05

print("\nThreshold\tPrecision_1\tRecall_1\tF1_1")
best_f1 = -1.0
best_threshold = 0.5  # default starting point

for thr in thresholds:
    # Convert probabilities to class predictions using current threshold
    y_pred_thr = (y_proba_svm >= thr).astype(int)

    precision = precision_score(y_test, y_pred_thr, pos_label=1, zero_division=0)
    recall    = recall_score(y_test, y_pred_thr, pos_label=1, zero_division=0)
    f1        = f1_score(y_test, y_pred_thr, pos_label=1, zero_division=0)

    print(f"{thr:.2f}\t\t{precision:.3f}\t\t{recall:.3f}\t\t{f1:.3f}")

    if f1 > best_f1:
        best_f1 = f1
        best_threshold = thr

print(f"\nBest threshold by F1 for class 1 (SVM): {best_threshold:.2f} (F1 = {best_f1:.3f})")

# =======================================
# FINAL CLASSIFICATION REPORT WITH BEST THRESHOLD
# =======================================

y_pred_svm_best_thr = (y_proba_svm >= best_threshold).astype(int)

print(f"\nClassification report (SVM RBF - test set, threshold={best_threshold:.2f}):")
print(classification_report(y_test, y_pred_svm_best_thr))

from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_auc_score, classification_report
from scipy.stats import randint, uniform

# ==========================
# CELL: XGBoost + RandomizedSearchCV
# ==========================

# 1) Base XGBoost model
xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    use_label_encoder=False,
    random_state=42,
    n_jobs=-1
)

# 2) Hyperparameter search space (reasonable ranges for tabular data)
param_dist_xgb = {
    "n_estimators": randint(100, 500),
    "max_depth": randint(3, 10),
    "learning_rate": uniform(0.01, 0.3),      # 0.01 to 0.31
    "subsample": uniform(0.6, 0.4),           # 0.6 to 1.0
    "colsample_bytree": uniform(0.6, 0.4),    # 0.6 to 1.0
    "min_child_weight": randint(1, 10),
    "gamma": uniform(0.0, 5.0)
}

# 3) RandomizedSearchCV
xgb_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist_xgb,
    n_iter=40,
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=42,
    verbose=1
)

xgb_search.fit(X_train, y_train)

print("Best CV AUC (XGBoost):", xgb_search.best_score_)
print("Best hyperparameters (XGBoost):")
print(xgb_search.best_params_)

# 4) Evaluate best XGBoost model on the test set
xgb_best = xgb_search.best_estimator_

y_pred_xgb = xgb_best.predict(X_test)
y_proba_xgb = xgb_best.predict_proba(X_test)[:, 1]

print("\nTest AUC (XGBoost):", roc_auc_score(y_test, y_proba_xgb))
print("\nClassification report (XGBoost - test set):")
print(classification_report(y_test, y_pred_xgb))

from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)
from scipy.stats import randint, uniform
import numpy as np

# ==========================
# XGBoost + RandomizedSearchCV
# ==========================

# 1) Base XGBoost model
xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    use_label_encoder=False,
    random_state=42,
    n_jobs=-1
)

# 2) Hyperparameter search space (reasonable ranges for tabular data)
param_dist_xgb = {
    "n_estimators": randint(100, 500),
    "max_depth": randint(3, 10),
    "learning_rate": uniform(0.01, 0.3),      # 0.01 to 0.31
    "subsample": uniform(0.6, 0.4),           # 0.6 to 1.0
    "colsample_bytree": uniform(0.6, 0.4),    # 0.6 to 1.0
    "min_child_weight": randint(1, 10),
    "gamma": uniform(0.0, 5.0)
}

# 3) RandomizedSearchCV
xgb_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist_xgb,
    n_iter=40,
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=42,
    verbose=1
)

# Fit XGBoost with hyperparameter search
xgb_search.fit(X_train, y_train)

print("Best CV AUC (XGBoost):", xgb_search.best_score_)
print("Best hyperparameters (XGBoost):")
print(xgb_search.best_params_)

# 4) Evaluate best XGBoost model on the test set
xgb_best = xgb_search.best_estimator_

# Predicted probabilities for the positive class (class 1)
y_proba_xgb = xgb_best.predict_proba(X_test)[:, 1]

print("\nTest AUC (XGBoost):", roc_auc_score(y_test, y_proba_xgb))

# =======================================
# THRESHOLD EXPLORATION SECTION
# =======================================

thresholds = np.arange(0.10, 0.91, 0.05)  # from 0.10 to 0.90 with step 0.05

print("\nThreshold\tPrecision_1\tRecall_1\tF1_1")
best_f1 = -1.0
best_threshold = 0.5  # default starting point

for thr in thresholds:
    # Convert probabilities to class predictions using current threshold
    y_pred_thr = (y_proba_xgb >= thr).astype(int)

    precision = precision_score(y_test, y_pred_thr, pos_label=1, zero_division=0)
    recall    = recall_score(y_test, y_pred_thr, pos_label=1, zero_division=0)
    f1        = f1_score(y_test, y_pred_thr, pos_label=1, zero_division=0)

    print(f"{thr:.2f}\t\t{precision:.3f}\t\t{recall:.3f}\t\t{f1:.3f}")

    # Track the threshold with the best F1 for the positive class
    if f1 > best_f1:
        best_f1 = f1
        best_threshold = thr

print(f"\nBest threshold by F1 for class 1 (XGBoost): {best_threshold:.2f} (F1 = {best_f1:.3f})")

# =======================================
# FINAL CLASSIFICATION REPORT WITH BEST THRESHOLD
# =======================================

y_pred_xgb_best_thr = (y_proba_xgb >= best_threshold).astype(int)

print(f"\nClassification report (XGBoost - test set, threshold={best_threshold:.2f}):")
print(classification_report(y_test, y_pred_xgb_best_thr))

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)
from scipy.stats import loguniform
import numpy as np

# ==========================
# MLP CLASSIFIER
# ==========================

mlp = MLPClassifier(
    max_iter=1000,
    random_state=42
)

param_dist_mlp = {
    "hidden_layer_sizes": [
        (16,),
        (32,),
        (64,),
        (32,16),
        (64,32)
    ],
    "alpha": loguniform(1e-5, 1e-1),
    "learning_rate_init": loguniform(1e-4, 1e-1)
}

mlp_search = RandomizedSearchCV(
    estimator=mlp,
    param_distributions=param_dist_mlp,
    n_iter=30,
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=42,
    verbose=1
)

mlp_search.fit(X_train, y_train)

print("Best CV AUC (MLP):", mlp_search.best_score_)
print("Best hyperparameters:")
print(mlp_search.best_params_)

mlp_best = mlp_search.best_estimator_

y_proba_mlp = mlp_best.predict_proba(X_test)[:,1]

print(
    "\nTest AUC (MLP):",
    roc_auc_score(y_test, y_proba_mlp)
)

thresholds = np.arange(0.10,0.91,0.05)

best_f1 = -1
best_threshold = 0.5

for thr in thresholds:

    y_pred_thr = (y_proba_mlp >= thr).astype(int)

    f1 = f1_score(
        y_test,
        y_pred_thr,
        pos_label=1,
        zero_division=0
    )

    if f1 > best_f1:
        best_f1 = f1
        best_threshold = thr

print(
    f"Best threshold: {best_threshold:.2f}"
)

y_pred_mlp = (
    y_proba_mlp >= best_threshold
).astype(int)

print(
    classification_report(
        y_test,
        y_pred_mlp
    )
)

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)
import numpy as np

# ==========================
# STACKING ENSEMBLE
# ==========================

estimators = [
    ("rf", rf_best),
    ("svm", svm_best),
    ("xgb", xgb_best),
    ("mlp", mlp_best)
]

stack_model = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(),
    cv=5,
    n_jobs=-1
)

stack_model.fit(
    X_train,
    y_train
)

y_proba_stack = stack_model.predict_proba(X_test)[:,1]

print(
    "\nTest AUC (Stacking):",
    roc_auc_score(
        y_test,
        y_proba_stack
    )
)

thresholds = np.arange(
    0.10,
    0.91,
    0.05
)

best_f1 = -1
best_threshold = 0.5

for thr in thresholds:

    y_pred_thr = (
        y_proba_stack >= thr
    ).astype(int)

    f1 = f1_score(
        y_test,
        y_pred_thr,
        pos_label=1,
        zero_division=0
    )

    if f1 > best_f1:
        best_f1 = f1
        best_threshold = thr

print(
    f"Best threshold: {best_threshold:.2f}"
)

y_pred_stack = (
    y_proba_stack >= best_threshold
).astype(int)

print(
    classification_report(
        y_test,
        y_pred_stack
    )
)

"""#Phase 4: Model comparation"""

from sklearn.metrics import (
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

results = []

models = {
    "Random Forest": (y_test, y_pred_rf_best_thr, y_proba_rf),
    "SVM": (y_test, y_pred_svm_best_thr, y_proba_svm),
    "XGBoost": (y_test, y_pred_xgb_best_thr, y_proba_xgb),
    "MLP": (y_test, y_pred_mlp, y_proba_mlp),
    "Stacking": (y_test, y_pred_stack, y_proba_stack)
}

for name, (y_true, y_pred, y_prob) in models.items():

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred
    ).ravel()

    sensitivity = tp / (tp + fn)

    specificity = tn / (tn + fp)

    results.append({
        "Model": name,
        "AUC": roc_auc_score(y_true, y_prob),
        "Sensitivity": sensitivity,
        "Specificity": specificity,
        "Precision": precision_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred)
    })

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="AUC",
    ascending=False
)

display(results_df.round(3))


print("\n")


ranking = results_df.copy()

ranking["AUC Rank"] = ranking["AUC"].rank(
    ascending=False
)

ranking["F1 Rank"] = ranking["F1"].rank(
    ascending=False
)

ranking["Global Rank"] = (
    ranking["AUC Rank"] +
    ranking["F1 Rank"]
)

ranking = ranking.sort_values(
    "Global Rank"
)

display(ranking)

metrics_plot = results_df.melt(
    id_vars="Model",
    value_vars=[
        "AUC",
        "Sensitivity",
        "Specificity",
        "Precision",
        "F1"
    ]
)

plt.figure(figsize=(12,6))

sns.barplot(
    data=metrics_plot,
    x="Model",
    y="value",
    hue="variable"
)

plt.title("Performance Metrics Comparison")

plt.ylabel("Score")

plt.legend(
    title="Metric",
    bbox_to_anchor=(1.05,1)
)

plt.show()

# en resumen, el más top es ... CHAN CHAN CHAN

best_auc_model = results_df.loc[
    results_df["AUC"].idxmax(),
    "Model"
]

best_f1_model = results_df.loc[
    results_df["F1"].idxmax(),
    "Model"
]

print(
    f"Best model by AUC: {best_auc_model}"
)

print(
    f"Best model by F1-score: {best_f1_model}"
)

"""#Phase 5: Interpretability & results"""

from sklearn.metrics import roc_curve, roc_auc_score

plt.figure(figsize=(10,8))

models_roc = {
    "Random Forest": y_proba_rf,
    "SVM": y_proba_svm,
    "XGBoost": y_proba_xgb,
    "MLP": y_proba_mlp,
    "Stacking": y_proba_stack
}

for name, probs in models_roc.items():

    fpr, tpr, _ = roc_curve(
        y_test,
        probs
    )

    auc_score = roc_auc_score(
        y_test,
        probs
    )

    plt.plot(
        fpr,
        tpr,
        label=f"{name} (AUC={auc_score:.3f})"
    )

plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves Comparison")
plt.legend()

plt.show()

from sklearn.metrics import confusion_matrix
import numpy as np

fig, axes = plt.subplots(
    2,
    3,
    figsize=(18,10)
)

axes = axes.flatten()

models = {

    "Random Forest": y_pred_rf_best_thr,
    "SVM": y_pred_svm_best_thr,
    "XGBoost": y_pred_xgb_best_thr,
    "MLP": y_pred_mlp,
    "Stacking": y_pred_stack

}

for ax, (name, pred) in zip(
    axes,
    models.items()
):

    cm = confusion_matrix(
        y_test,
        pred
    )

    cm_percent = (
        cm.astype("float")
        / cm.sum()
        * 100
    )

    labels = np.array([
        [
            f"{cm[i,j]}\n({cm_percent[i,j]:.1f}%)"
            for j in range(cm.shape[1])
        ]
        for i in range(cm.shape[0])
    ])

    sns.heatmap(
        cm,
        annot=labels,
        fmt="",
        cmap="Blues",
        ax=ax
    )

    ax.set_title(name)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")

fig.delaxes(axes[5])

plt.tight_layout()

plt.show()

!pip install shap

import shap
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import tempfile

explainer = shap.TreeExplainer(xgb_best)
shap_values = explainer.shap_values(X_test)

print("SHAP values shape:")
print(shap_values.shape)

tmp1 = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
tmp2 = tempfile.NamedTemporaryFile(suffix=".png", delete=False)

plt.figure()
shap.summary_plot(
    shap_values,
    X_test,
    show=False
)
plt.savefig(tmp1.name, bbox_inches="tight")
plt.close()

plt.figure()
shap.summary_plot(
    shap_values,
    X_test,
    plot_type="bar",
    show=False
)
plt.savefig(tmp2.name, bbox_inches="tight")
plt.close()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

axes[0].imshow(mpimg.imread(tmp1.name))
axes[0].axis("off")
axes[0].set_title("SHAP Summary")

axes[1].imshow(mpimg.imread(tmp2.name))
axes[1].axis("off")
axes[1].set_title("SHAP Feature Importance")

plt.tight_layout()
plt.show()

pacient = 12
shap.plots.waterfall(
    shap.Explanation(
        values=shap_values[pacient],
        base_values=explainer.expected_value,
        data=X_test.iloc[pacient],
        feature_names=X_test.columns
    )
)

# FEATURE IMPORTANCE XGBOOST

import pandas as pd
import matplotlib.pyplot as plt

importance = pd.DataFrame({

    "Feature": X_test.columns,
    "Importance": xgb_best.feature_importances_

})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

display(
    importance.head(20)
)

plt.figure(figsize=(8,6))

plt.barh(
    importance["Feature"][:15],
    importance["Importance"][:15]
)

plt.gca().invert_yaxis()

plt.title("XGBoost Feature Importance")

plt.tight_layout()

plt.show()